version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    env_file:
      - ./app.env
    ports:
      - '6000:27017'
    volumes:
      - mongodb:/data/db
  
  redis:
    image: redis:alpine
    container_name: redisdb
    ports:
      - '6379:6379'
    volumes:
      - redisdb:/data

volumes:
  mongodb:
  redisdb: